// This file is auto-generated by the whisp2424/anilist-mcp integration.
// For more information, please see the project documentation.
import {
  get_anime,
  get_manga,
  get_character,
  get_staff,
  search_anime,
  search_manga,
  search_character,
  search_staff,
} from "../api/anilist";

export const media_tools = {
  get_anime,
  get_manga,
  get_character,
  get_staff,
  search_anime,
  search_manga,
  search_character,
  search_staff,
};
